"""Regenerate everything under demo/ from the local archive.

    OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 \
        uv run python scripts/make_demos.py

The demo files are committed so a reader can see real output without running
anything, and this script exists so nobody has to trust that they were not typed
by hand. Every number in demo/ comes from here, and here reads only the MIT
archive - no network, no API key, no held-out season.
"""

from __future__ import annotations

import json
import math
import subprocess
from datetime import UTC, datetime
from pathlib import Path

import polars as pl

from cfbpoll.backtest import walkforward
from cfbpoll.config import DEFAULT_CONFIG_PATH, config_hash, load_config
from cfbpoll.ingest import windows
from cfbpoll.ingest.sportsdataverse import load_games
from cfbpoll.model import l2_results
from cfbpoll.publish import poll as poll_mod

ROOT = Path(__file__).resolve().parents[1]
DEMO = ROOT / "demo"

TUNE_SEASONS = [2021, 2022, 2023]
SYSTEMS = ["l2", "colley", "srs", "elo", "walker", "winpct", "home_team"]
DEMO_SEASON = 2023
DEMO_WEEK = 10


def git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
            cwd=ROOT,
        ).stdout.strip()
    except Exception:
        return "unknown"


def provenance(extra: str = "") -> str:
    return (
        f"Generated by `scripts/make_demos.py` at {datetime.now(UTC):%Y-%m-%d} from the local "
        f"SportsDataverse MIT archive (2021-2025 `cfb_schedules_*`).\n"
        f"Code `{git_sha()}` - config `configs/default.toml` sha256 "
        f"`{config_hash(DEFAULT_CONFIG_PATH)[:16]}...`{extra}\n"
    )


def top25() -> str:
    cfg = load_config()
    games = load_games([DEMO_SEASON], universe=str(cfg["model"]["fit_universe"]))
    window = windows.games_through(games, season=DEMO_SEASON, week=DEMO_WEEK, season_type="regular")
    fit = l2_results.fit(window, cfg)
    ratings = poll_mod.ratings_frame(fit.ratings, window)
    table = poll_mod.poll_frame(ratings, restrict_to=poll_mod.fbs_teams(window))

    fbs_only = window.filter((pl.col("home_class") == "fbs") & (pl.col("away_class") == "fbs"))
    lines = [
        f"# L2 results core, v0 - {DEMO_SEASON} through regular week {DEMO_WEEK}",
        "",
        "**This is not the finished poll.** It is layer 2 of four: ridge regression on",
        "compressed scoring margin, and nothing else. There is no efficiency layer, no",
        "blend, and no resume rating, so this is a *power* rating - what the model thinks",
        "of a team's play - rather than the *deserve* rating that report 02 §3.5 argues",
        "should be the headline. Read it as a demonstration that the machinery works on",
        "real football, not as a ranking anyone should argue about yet.",
        "",
        "## What went into it",
        "",
        "| | |",
        "|---|---|",
        f"| Games in the fit | {fit.n_games:,} |",
        f"| ... of which FBS-vs-FBS | {fbs_only.height:,} |",
        f"| Teams with their own coefficient | {fit.n_teams} |",
        f"| Ridge lambda (chosen by 5-fold CV on games) | {fit.lam:g} |",
        f"| Home field, fitted and unpenalised | {fit.home_field:.3f} response points |",
        f"| Compression scale C | {cfg['margin']['c']:g} |",
        f"| Win premium beta_w | {cfg['margin']['beta_w']:g} |",
        "",
        "Every FCS team in the schedule holds its own coefficient in the same fit under",
        "the same penalty - no pooled node (report 02 §3.7). They are omitted from the",
        "table below because this is a college football poll, not because they are hidden:",
        "`out/ratings_live.parquet` carries all "
        f"{ratings.height} teams in the fit, each labelled with its classification.",
        "",
        "## Top 25",
        "",
        "| # | Team | Record | Rating |",
        "|---:|---|:---:|---:|",
    ]
    for row in table.head(25).iter_rows(named=True):
        lines.append(
            f"| {row['rank']} | {row['team']} | {row['wins']}-{row['losses']} "
            f"| {row['rating']:.2f} |"
        )

    lines += [
        "",
        "## Reading it honestly",
        "",
        "Undefeated Georgia sits at "
        f"{table.filter(pl.col('team') == 'Georgia')['rank'][0]}"
        " and undefeated Florida State at "
        f"{table.filter(pl.col('team') == 'Florida State')['rank'][0]}"
        ", both behind one-loss Oregon and Penn State. That is not a bug - it is the",
        "predictive/deserved distinction doing exactly what report 02 §3.5 says it does.",
        "A margin-based power rating discounts a run of narrow wins; a resume rating (L4,",
        "not built yet) does the opposite. The 2023 season is the sharpest available test",
        "of that difference, which is why it is the demo season.",
        "",
        "Kansas State at "
        f"{table.filter(pl.col('team') == 'Kansas State')['rank'][0]}"
        " on a 6-3 record is the same effect in the other direction: three",
        "close losses to good teams, and a model with no win premium large enough to",
        "punish them. beta_w = 3.0 is the knob that controls exactly this, it is published",
        "on every artifact, and report 02 §7.4 is explicit that its value is a decision for",
        "people rather than for a grid search.",
        "",
        "## Reproduce it",
        "",
        "```",
        f"uv run cfbpoll rank --season {DEMO_SEASON} --through-week {DEMO_WEEK} --out out/",
        "```",
        "",
        provenance(),
    ]
    return "\n".join(lines)


def _fmt(value: float | None, spec: str) -> str:
    if value is None:
        return "-"
    return format(value, spec)


def backtest_report() -> str:
    result = walkforward.run_backtest(seasons=TUNE_SEASONS, systems=SYSTEMS)
    protocol = result["protocol"]
    systems = result["systems"]
    order = ["l2", "srs", "elo", "colley", "winpct", "random_walker", "home_team"]
    label = {
        "l2": "**L2 (ours)**",
        "srs": "SRS (±24/±7)",
        "elo": "Elo (K=25, MOV)",
        "colley": "Colley",
        "winpct": "Win %",
        "random_walker": "Random walker",
        "home_team": "Home team wins",
    }

    def table(cut: str, caption: str) -> list[str]:
        rows = [
            "",
            f"### {caption}",
            "",
            "| System | n | SU % | MAE | RMSE | Brier | Log loss | Max calib. dev. |",
            "|---|---:|---:|---:|---:|---:|---:|---:|",
        ]
        for name in order:
            block = systems[name][cut].get("fbs_vs_fbs")
            if not block:
                continue
            rows.append(
                f"| {label[name]} | {block['n_games']} | {block['su_accuracy'] * 100:.2f} "
                f"| {block['mae']:.3f} | {block['rmse']:.3f} | {block['brier']:.4f} "
                f"| {block['log_loss']:.4f} | {block['max_calibration_deviation_pp']:.2f} pp |"
            )
        return rows

    lines = [
        "# Walk-forward backtest, 2021-2023 (tune seasons only)",
        "",
        "**2024 (validate) and 2025 (holdout) are untouched.** The harness refuses to score",
        "2025 without an explicit `--unlock-holdout`, and no code path in this repository",
        "passes it (report 02 §5.1). Nothing below has been tuned against anything: the",
        "config's starting values are the research report's, and no grid has been searched.",
        "",
        "## Protocol",
        "",
        "- To predict week N, fit on data through week N-1 of the **same season only**. No",
        "  prior seasons, ever (constraint 2), and no future games (`prior_seasons_used`:",
        f"  `{protocol['prior_seasons_used']}`).",
        "- Evaluation universe: FBS-vs-FBS. FBS-vs-FCS games, non-CFP bowls and CFP games",
        "  are scored separately below, because they measure different things.",
        f"- Win probability = Phi(margin / sigma) with sigma = {protocol['sigma']}"
        " (report 02 §3.4, §5.4).",
        "- Every system's ratings are mapped to the points scale by one OLS per system per",
        "  week, fitted on the out-of-sample predictions already accumulated that season.",
        "  Elo lives on a 400-point logit scale and win percentage on [0, 1]; without this",
        "  the MAE column would be meaningless for five of the seven rows. Straight-up",
        "  accuracy is unaffected - it is invariant to a positive affine map.",
        "",
        "## The headline table",
        "",
        f"Weeks {protocol['headline_start_week']}+ is the window the project actually intends",
        "to publish (report 02 §4): before then the schedule graph is barely connected and a",
        "zero-prior system openly does not know anything yet. Both cuts are shown, because",
        "reporting only the flattering one would be the exact failure this project exists to",
        "avoid.",
    ]
    lines += table("segments_from_headline_week", "Weeks 5+ (the published window)")
    lines += table("segments", "Weeks 2+ (everything the harness can score)")

    lines += [
        "",
        "## What that says",
        "",
        "- From week 5 on, L2 leads **every** predictive metric: accuracy, MAE, RMSE, Brier,",
        "  log loss and calibration. That is the Barrow et al. result (report 02 §2.15) -",
        "  least squares on score differential is the best-supported family for college",
        "  football - reproduced on 2021-2023 with an independent implementation.",
        "- Over weeks 2+ the ordering is not clean: SRS edges L2 on MAE and Elo on accuracy,",
        "  both by fitting the near-noise weeks slightly better. A zero-prior system has no",
        "  business being confident in September and this is the number that shows it.",
        "- The random walker underperforms here, which is a real disagreement with Barrow et",
        "  al. Two candidate explanations, neither verified: their implementation is",
        "  full-season rather than walk-forward, and this one is margin-blind by",
        "  construction. It stays in the baseline set.",
        "- Win percentage is beaten decisively on margin error by everything with an",
        "  opponent adjustment, which is what constraint 3 exists to buy.",
        "- Non-CFP bowls are worse than a coin flip for every system in the table. That is",
        "  the roster-availability problem of report 02 §3.8 showing up as a number, and it",
        "  is why those games carry a 0.25 weight in the fit and are never pooled into the",
        "  headline.",
        "",
        "## Retrodictive violations and stability",
        "",
        "Violations are games whose loser the final full-season rating ranks above the",
        "winner - the canonical retrodictive metric (report 02 §2.12). Churn is the mean",
        "absolute week-over-week rank change across FBS teams.",
        "",
        "| System | Violation rate | Mean rank churn |",
        "|---|---:|---:|",
    ]
    for name in order:
        block = systems[name]
        lines.append(
            f"| {label[name]} | {_fmt(block['retrodictive_violation_rate'], '.4f')} "
            f"| {_fmt(block['rank_churn']['mean_all'], '.2f')} |"
        )

    l2_v = systems["l2"]["retrodictive_violation_rate"]
    colley_v = systems["colley"]["retrodictive_violation_rate"]
    srs_v = systems["srs"]["retrodictive_violation_rate"]
    lines += [
        "",
        f"**L2 does not yet clear the gate on violations.** It is at {l2_v:.4f} against",
        f"Colley's {colley_v:.4f}, and configs/default.toml asks for a rate at or below both",
        f"Colley and SRS (it beats SRS, {srs_v:.4f}). This is expected and it is the argument",
        "for L4: a margin-based power rating is not trying to respect results, and win-loss",
        "systems win the violations metric almost by construction. The resume layer is where",
        "that number is supposed to move. Reporting it as a miss now, rather than after L4",
        "makes it look good, is the point of building the harness second.",
        "",
        "## Segments reported separately",
        "",
        "| Segment | n | SU % | MAE | Why it is separate |",
        "|---|---:|---:|---:|---|",
    ]
    why = {
        "fbs_vs_fbs": "the evaluation universe",
        "fbs_vs_fcs": "easy games; pooling them in inflates accuracy",
        "bowl": "non-CFP bowls have a systematic roster-availability problem (§3.8)",
        "cfp": "rosters intact, but a handful of games a year",
    }
    for segment, block in systems["l2"]["segments"].items():
        lines.append(
            f"| `{segment}` | {block['n_games']} | {block['su_accuracy'] * 100:.2f} "
            f"| {block['mae']:.3f} | {why[segment]} |"
        )

    early = [c for c in result["connectivity"] if c["season"] == 2023 and c["week"] <= 3]
    late = [c for c in result["connectivity"] if c["season"] == 2023 and c["week"] == 10]
    lines += [
        "",
        "## Why the early weeks look the way they do",
        "",
        "The schedule graph is the reason, and it is measurable rather than an excuse.",
        "Each row is the training window a fit for that week would have seen, in 2023:",
        "",
        "| Fit window | Teams | Components | Largest component |",
        "|---|---:|---:|---:|",
    ]
    for c in (early[:2] + late)[:3]:
        lines.append(
            f"| 2023 before week {c['week']} | {c['n_teams']:.0f} | {c['n_components']:.0f} "
            f"| {c['largest_component_share'] * 100:.1f}% |"
        )
    lines += [
        "",
        "A fragmented graph is exactly what makes SRS near-singular and a zero-prior",
        "ranking wild in September. Our ridge term keeps the system solvable throughout -",
        "L + lambda*I is positive definite for any lambda > 0 - but solvable is not the",
        "same as informative, which is why report 02 §4 recommends publishing a",
        "connectivity report instead of a poll until week 5.",
        "",
        "## Reproduce it",
        "",
        "```",
        "uv run cfbpoll backtest --systems l2,colley,srs,elo,walker,winpct --seasons 2021-2023",
        "```",
        "",
        "The full metrics tree, including the per-week table and every calibration decile,",
        "is written to `out/backtest_metrics.json`.",
        "",
        provenance(),
    ]
    return "\n".join(lines)


def _valid_json(obj: object) -> object:
    """NaN is not JSON. A week with no shared teams has no churn; that is a null."""
    if isinstance(obj, dict):
        return {k: _valid_json(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_valid_json(v) for v in obj]
    if isinstance(obj, float) and not math.isfinite(obj):
        return None
    return obj


def main() -> None:
    DEMO.mkdir(exist_ok=True)
    (DEMO / f"{DEMO_SEASON}-w{DEMO_WEEK}-top25.md").write_text(top25(), encoding="utf-8")
    (DEMO / "backtest-2021-2023.md").write_text(backtest_report(), encoding="utf-8")

    result = walkforward.run_backtest(seasons=TUNE_SEASONS, systems=SYSTEMS)
    (DEMO / "backtest-2021-2023.json").write_text(
        json.dumps(
            _valid_json({"protocol": result["protocol"], "systems": result["systems"]}),
            indent=2,
            sort_keys=True,
            default=float,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {sorted(p.name for p in DEMO.iterdir())}")


if __name__ == "__main__":
    main()
