"""Regenerate everything under demo/ from the local archive.

    OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 \
        uv run python scripts/make_demos.py

The demo files are committed so a reader can see real output without running
anything, and this script exists so nobody has to trust that they were not typed
by hand. Every number in demo/ comes from here, and here reads only the MIT
archive - no network, no API key, no held-out season.

ONE EXCEPTION, and it is loud on purpose: `CFP_FINAL` below is the committee's
own published ranking, transcribed for COMPARISON. It is a human poll. It is
never an input, never a fitting target, and never touches a design matrix - it
lives in a demo generator rather than in `src/` for exactly that reason
(constraint 1; report 02 §5.5 says report the disagreements and let the
disagreements be the product).
"""

from __future__ import annotations

import json
import math
import subprocess
from datetime import UTC, datetime
from pathlib import Path

import polars as pl

from cfbpoll.backtest import walkforward
from cfbpoll.config import DEFAULT_CONFIG_PATH, config_hash, load_config
from cfbpoll.ingest import windows
from cfbpoll.ingest.sportsdataverse import load_games
from cfbpoll.model import l4_resume, retro
from cfbpoll.publish import poll as poll_mod

ROOT = Path(__file__).resolve().parents[1]
DEMO = ROOT / "demo"

TUNE_SEASONS = [2021, 2022, 2023]
SYSTEMS = ["resume", "l2", "colley", "srs", "elo", "walker", "winpct", "home_team"]
DEMO_SEASON = 2023
DEMO_WEEK = 10

#: COMPARISON ONLY - a human poll, never an input (constraint 1). Verified against
#: the official CFP releases, transcribed in report 02 §5.5.
#: https://collegefootballplayoff.com/news/2023/12/3/cfp-rankings-2023-1203.aspx
#: https://collegefootballplayoff.com/news/2021/12/5/cfp-rankings-2021-1205.aspx
CFP_FINAL: dict[int, list[tuple[int, str, str]]] = {
    2021: [
        (1, "Alabama", "12-1"),
        (2, "Michigan", "12-1"),
        (3, "Georgia", "12-1"),
        (4, "Cincinnati", "13-0"),
        (5, "Notre Dame", "11-1"),
        (6, "Ohio State", "10-2"),
    ],
    2023: [
        (1, "Michigan", "13-0"),
        (2, "Washington", "13-0"),
        (3, "Texas", "12-1"),
        (4, "Alabama", "12-1"),
        (5, "Florida State", "13-0"),
    ],
}

#: The seasons whose archive carries no postseason rows at all. Any demo that
#: touches one must say so (docs/data-findings.md; ingest/sportsdataverse.py).
NO_POSTSEASON = (2021, 2022)

POSTSEASON_CAVEAT = (
    "> **Data caveat, stated up front.** The `cfb_schedules_*` archive carries **no "
    "postseason rows at all** for {seasons}: `season_type` has one value, `regular`. "
    'So "final" in this document means **through conference championship weekend** — '
    "no bowls, no playoff. Every number below is computed on that window and none of "
    "it should be read as though it included the postseason."
)


def git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
            cwd=ROOT,
        ).stdout.strip()
    except Exception:
        return "unknown"


def provenance(extra: str = "") -> str:
    return (
        f"Generated by `scripts/make_demos.py` at {datetime.now(UTC):%Y-%m-%d} from the local "
        f"SportsDataverse MIT archive (2021-2025 `cfb_schedules_*`).\n"
        f"Code `{git_sha()}` - config `configs/default.toml` sha256 "
        f"`{config_hash(DEFAULT_CONFIG_PATH)[:16]}...`{extra}\n"
    )


def power_v0_note() -> list[str]:
    """The one caveat every résumé demo carries: Power is L2, not L3."""
    return [
        "> **Power is L2, version v0.** Report 02 §3.4 reads opponent quality off the L3",
        "> blend of efficiency and results. L1 and L3 are not built (report 02 Appendix B",
        "> puts them fourth and fifth), so the Power rating here is the L2 results core",
        "> rescaled to points by one no-intercept OLS per fit. Every artifact stamps",
        '> `power_source = "L2"`, `power_version = "v0"`. When L3 lands, this number',
        "> changes and the résumé equation does not.",
    ]


def saturation_note() -> list[str]:
    return [
        "**Why every undefeated team shows 60.00 and a `*`.** `E[W|q]` approaches the",
        "number of games from below, so an undefeated team's résumé equation has **no",
        "finite root** — the results are consistent with arbitrarily high quality. That is",
        "Bradley-Terry's separation problem (report 02 §2.10) in deterministic clothes, and",
        "the published bracket `q_bounds = [-60, +60]` is the regularization: it is where an",
        "unbounded estimate gets truncated, at a number printed in the config. Two",
        "consequences, both stated rather than hidden:",
        "",
        "1. On the wins-based résumé **no one-loss team can outrank an undefeated team**,",
        "   however soft the unbeaten schedule.",
        "2. Saturated teams all land on the same value, so the order among them comes from",
        "   the **margin-aware résumé**, which is finite for every team and is in the table.",
        '   The rule is `[resume].saturation_tiebreak = "margin"`.',
    ]


# --------------------------------------------------------------------------- helpers


def season_frames(season: int) -> tuple[pl.DataFrame, list[windows.Bucket], pl.DataFrame]:
    cfg = load_config()
    games = load_games([season], universe=str(cfg["model"]["fit_universe"]))
    buckets = windows.season_buckets(games, season)
    grid = retro.grid(games, season, cfg, buckets)
    return games, buckets, grid


def ranked(frame: pl.DataFrame, eval_order: int) -> pl.DataFrame:
    return frame.filter((pl.col("eval_order") == eval_order) & pl.col("rank").is_not_null())


def with_power_rank(frame: pl.DataFrame) -> pl.DataFrame:
    return (
        frame.sort(["power", "team"], descending=[True, False])
        .with_row_index("power_rank", offset=1)
        .with_columns(pl.col("power_rank").cast(pl.Int32))
    )


def poll_table(live: pl.DataFrame, hind: pl.DataFrame, n: int = 25) -> list[str]:
    """The published shape: résumé ranks, Power beside them, both surfaces."""
    ranked_by_power = with_power_rank(live)
    power_rank = dict(
        zip(
            ranked_by_power["team"].to_list(),
            ranked_by_power["power_rank"].to_list(),
            strict=True,
        )
    )
    table = poll_mod.headline_frame(live, hind)
    rows = [
        "| # | Team | Rec | Résumé | Margin résumé | Power | Gap | Power # | Hindsight # |",
        "|---:|---|:---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in table.head(n).iter_rows(named=True):
        mark = "\\*" if row["saturated"] else ""
        delta = row["rank_delta"]
        arrow = "—" if delta == 0 else (f"▲{delta}" if delta > 0 else f"▼{-delta}")
        rows.append(
            f"| {row['rank']} | {row['team']} | {row['wins']}-{row['losses']} "
            f"| {row['resume']:.2f}{mark} | {row['resume_margin']:.2f} "
            f"| {row['power']:.2f} | {row['gap']:+.2f} "
            f"| {power_rank.get(row['team'], 0)} "
            f"| {row['rank_hindsight']} ({arrow}) |"
        )
    return rows


def cfp_table(season: int) -> list[str]:
    rows = [
        "| CFP # | Team | Rec |",
        "|---:|---|:---:|",
    ]
    rows += [f"| {r} | {t} | {rec} |" for r, t, rec in CFP_FINAL[season]]
    return rows


def ordinal(n: int) -> str:
    if 10 <= n % 100 <= 20:
        return f"{n}th"
    return f"{n}{ {1: 'st', 2: 'nd', 3: 'rd'}.get(n % 10, 'th') }".replace(" ", "")


def team_row(frame: pl.DataFrame, team: str) -> dict:
    return with_power_rank(frame).filter(pl.col("team") == team).row(0, named=True)


# ------------------------------------------------------------- 1. the flagship demo


def final_poll_2023() -> str:
    cfg = load_config()
    season = 2023
    games, buckets, grid = season_frames(season)
    regular = [b for b in buckets if b.season_type == "regular"]
    evaluated = regular[-1]
    final = buckets[-1]

    live_all, hind_all = retro.surfaces(grid)
    live = ranked(live_all, evaluated.order)
    hind = ranked(hind_all, evaluated.order)

    fsu_live = team_row(live, "Florida State")
    fsu_hind = team_row(hind, "Florida State")
    uga_live = team_row(live, "Georgia")
    uga_hind = team_row(hind, "Georgia")
    bama = team_row(live, "Alabama")
    liberty = team_row(live, "Liberty")
    michigan = team_row(live, "Michigan")

    fbs = games.filter((pl.col("home_class") == "fbs") & (pl.col("away_class") == "fbs"))
    n_saturated = int(live.filter(pl.col("saturated") == 1).height)

    lines = [
        f"# The {season} final poll — résumé and power, live and hindsight",
        "",
        "This is the headline product: teams ranked by the **L4 résumé rating**, which is",
        "the quality `q` whose *expected* results against that exact schedule equal the",
        "*actual* ones, with the **Power rating** and the résumé-minus-power gap beside",
        "every team (report 02 §3.4, §3.5). It is shown twice — as the poll would have read",
        "on championship Saturday, and as it reads with the whole season's answers in hand.",
        "",
    ]
    lines += power_v0_note()
    lines += [
        "",
        "## The window, precisely",
        "",
        "| | |",
        "|---|---|",
        f"| Evaluation week **N** | `{evaluated.label}` — through conference championships |",
        f"| Live data window **K = N** | R(N, N), {evaluated.label} |",
        f"| Hindsight data window **K = final** | R(N, final), `{final.label}` — includes bowls "
        "and the playoff |",
        f"| Games in the season frame | {games.height:,} |",
        f"| ... of which FBS-vs-FBS | {fbs.height:,} |",
        f"| Ranked (FBS) teams | {live.height} |",
        f"| sigma | {cfg['resume']['sigma']} points |",
        f"| Compression C / win premium beta_w | {cfg['margin']['c']:g} / "
        f"{cfg['margin']['beta_w']:g} |",
        "",
        "The evaluation week is championship Saturday and **not** the post-bowl end of the",
        "season, because `[weights].final_poll_excludes_non_cfp_bowls = true`: non-CFP bowls",
        "have a systematic roster-availability problem (report 02 §3.8), so the final",
        "published poll is the one computed before them. That also makes this poll directly",
        "comparable to the committee's final ranking, which was released the same weekend.",
        "The hindsight column *does* see the postseason — non-CFP bowls at weight",
        f"{cfg['weights']['bowl_non_cfp']}, playoff games at full weight — because hindsight is",
        "allowed to know things the live poll could not.",
        "",
        "## The poll",
        "",
        "Résumé is the rank. `Power #` is where the same team sits on the power rating, so",
        "the disagreement between the two is readable on every row. `Hindsight #` is R(N,",
        "final): the same week, re-scored with the season's answers.",
        "",
    ]
    lines += poll_table(live, hind, 25)
    lines += ["", *saturation_note(), ""]

    lines += [
        "## The test this season exists for: Florida State",
        "",
        "Florida State finished 13-0, won the ACC, and was left out of a four-team playoff",
        "for the first time in the CFP era. Here is what a transparent system says, on both",
        "numbers and both surfaces:",
        "",
        "| | Résumé rank | Résumé | Margin résumé | Power rank | Power | Gap |",
        "|---|---:|---:|---:|---:|---:|---:|",
        f"| **Live** R(N, N) | {fsu_live['rank']} | {fsu_live['resume']:.2f}\\* "
        f"| {fsu_live['resume_margin']:.2f} | {fsu_live['power_rank']} "
        f"| {fsu_live['power']:.2f} | {fsu_live['gap']:+.2f} |",
        f"| **Hindsight** R(N, final) | {fsu_hind['rank']} | {fsu_hind['resume']:.2f}\\* "
        f"| {fsu_hind['resume_margin']:.2f} | {fsu_hind['power_rank']} "
        f"| {fsu_hind['power']:.2f} | {fsu_hind['gap']:+.2f} |",
        "",
        f"**The two numbers disagree by {fsu_hind['power_rank'] - fsu_hind['rank']} places, and",
        "that disagreement is the entire product.** The résumé says Florida State did the",
        f"{ordinal(fsu_hind['rank'])}-best job of beating the schedule in front of it — "
        "nobody with a loss can",
        "outrank an unbeaten team on that number, by construction. The power rating says its",
        f"play was worth about {fsu_hind['power']:.1f} points against an average team, "
        f"{fsu_hind['power_rank']}th",
        "in the country, because it won a lot of close games. Both are true. The committee",
        "was answering a third question — who would we most like to watch play for a title —",
        "and it is the only one of the three that is not written down anywhere.",
        "",
        "Note what hindsight does **not** do here: it does not move Florida State. The",
        "Orange Bowl, in which a Florida State team missing 33 players lost 63-3, is in the",
        f"hindsight *Power* fit at weight {cfg['weights']['bowl_non_cfp']} and is **not** in "
        "the résumé, because the",
        "résumé window is frozen at week N (variant A, report 02 §3.6). A poll that let the",
        "January consequences of the December decision retroactively justify the December",
        "decision would be circular, and this construction cannot do it.",
        "",
        "## Georgia, and the sanity check",
        "",
        f"Georgia was 12-1 with its only loss in the SEC championship game. Résumé "
        f"{uga_live['rank']} live,",
        f"{uga_hind['rank']} in hindsight; power {uga_live['power_rank']} live and "
        f"{uga_hind['power_rank']} in hindsight. That gap runs the other way from Florida",
        "State's — the model thinks Georgia *played* better than its résumé, which is what",
        "losing one game to a good opponent looks like from the inside.",
        "",
        f"Alabama, whom the committee took over Florida State, is résumé {bama['rank']} and "
        f"power {bama['power_rank']}",
        "here (live). On the power number the committee and this model broadly agree about",
        "Alabama; on the résumé number they do not agree about what a 13-0 season is worth.",
        "",
        "## The uncomfortable row",
        "",
        f"Liberty went 13-0 in Conference USA and lands at résumé {liberty['rank']} with a "
        f"power rating of",
        f"{liberty['power']:.2f} — {ordinal(liberty['power_rank'])}. This is the saturation "
        "property doing exactly what it says it",
        "does, and it is the single strongest argument against publishing the wins-based",
        "résumé alone. The margin-aware résumé, in the same table, puts Liberty at",
        f"{liberty['resume_margin']:.2f} against Michigan's "
        f"{michigan['resume_margin']:.2f}, which is a far more useful",
        "sentence about the season. Report 02 §3.4 says to publish both because they answer",
        "different questions; this row is why that instruction is load-bearing rather than",
        "decorative.",
        "",
        "## The committee's final ranking, for comparison — **not** a target",
        "",
        "Fitting toward committee agreement would reintroduce human-poll bias through the",
        "back door: a subtle but complete violation of constraint 1. This table is here so",
        "the disagreements are visible, and the disagreements are the product (report 02",
        "§5.5).",
        "",
    ]
    lines += cfp_table(season)
    lines += [
        "",
        "Sources: the official CFP release of 3 December 2023.",
        "",
        "## Reproduce it",
        "",
        "```",
        f"uv run cfbpoll rank --season {season} --through-week {evaluated.week} --out out/",
        f"uv run cfbpoll grid --season {season} --out out/",
        "```",
        "",
        f"`{n_saturated}` ranked teams are saturated in the live poll. The full "
        f"{grid.height:,}-row R(N, K)",
        "triangle, both surfaces and the movers table are written by the second command.",
        "",
        provenance(),
    ]
    return "\n".join(lines)


# ------------------------------------------------------------ 2. the retro movers


def retro_movers_2023() -> str:
    cfg = load_config()
    season = 2023
    _, buckets, grid = season_frames(season)
    live, hind = retro.surfaces(grid)
    headline_week = int(cfg["publication"]["headline_start_week"])
    published = [b.order for b in buckets if b.season_type == "regular" and b.week >= headline_week]

    movers = retro.movers(live, hind).filter(pl.col("eval_order").is_in(published))
    biggest = movers.sort(["abs_rank_delta", "resume_delta"], descending=True).head(15)
    curve = retro.divergence(live, hind).filter(pl.col("eval_order").is_in(published))

    lines = [
        f"# {season} retroactive movers — who the model was wrong about, in its own words",
        "",
        'Report 02 §3.6 calls this view *"the most differentiated thing this project can',
        'ship"*, and it costs nothing extra once the R(N, K) grid exists. Every row is one',
        "team in one week, ranked twice by the same estimator: once with the data available",
        "that week (`R(N, N)`, the poll as published) and once with the whole season's",
        "answers substituted in for opponent quality (`R(N, final)`, hindsight variant A).",
        "",
        "**Nothing about the team's own results changes between the two columns.** The",
        "résumé window is frozen at week N; only the *opponents' Power ratings* are",
        "replaced. That is the whole retroactive mechanism, and it is one substitution",
        "(report 02 §3.4).",
        "",
    ]
    lines += power_v0_note()
    lines += [
        "",
        f"## Biggest moves, weeks {headline_week}+ (the published window)",
        "",
        "▲ means the live poll **under**-rated the team: the opponents it had beaten turned",
        "out to be better than they looked at the time.",
        "",
        "| Week | Team | Live # | Hindsight # | Move | Résumé live → hindsight "
        "| Power live → hindsight |",
        "|---|---|---:|---:|---:|---:|---:|",
    ]
    for row in biggest.iter_rows(named=True):
        delta = row["rank_delta"]
        arrow = f"▲{delta}" if delta > 0 else f"▼{-delta}"
        lines.append(
            f"| `{row['eval_label']}` | {row['team']} | {row['rank_live']} "
            f"| {row['rank_hindsight']} | {arrow} "
            f"| {row['resume_live']:.2f} → {row['resume_hindsight']:.2f} "
            f"| {row['power_live']:.2f} → {row['power_hindsight']:.2f} |"
        )

    first = curve.row(0, named=True)
    last = curve.row(curve.height - 1, named=True)
    means = curve["mean_abs_rank_delta"].to_list()
    monotone = all(a >= b for a, b in zip(means, means[1:], strict=False))
    lines += [
        "",
        "## The divergence curve, which is a falsifiable claim",
        "",
        "Report 02 §5.2 lists retro-vs-live divergence as a **stability** metric and says it",
        "must decline in N, or the retroactive product itself is unstable. The later the",
        "week, the less the rest of the season can teach us about it. Here is the curve, for",
        f"all {first['n_teams']} ranked teams:",
        "",
        "| Evaluation week | Mean \\|Δrank\\| | Max \\|Δrank\\| |",
        "|---|---:|---:|",
    ]
    for row in curve.iter_rows(named=True):
        lines.append(
            f"| `{row['eval_label']}` | {row['mean_abs_rank_delta']:.2f} "
            f"| {row['max_abs_rank_delta']} |"
        )
    lines += [
        "",
        f"Mean divergence falls from **{first['mean_abs_rank_delta']:.2f} places** at "
        f"`{first['eval_label']}` to "
        f"**{last['mean_abs_rank_delta']:.2f}** at `{last['eval_label']}`"
        + (
            ", monotonically."
            if monotone
            else ", and the decline is monotone except at the very end of the season, where"
            " the final data window adds the postseason and moves a handful of teams that"
            " the previous window had already settled."
        ),
        "",
        "That shape is the thing to check, not the individual rows. A retroactive poll whose",
        "week-12 ranking still moved 6 places in hindsight would be telling you its week-12",
        "ranking was never worth reading.",
        "",
        "## What the big movers have in common",
        "",
        "They are almost all outside the top 25, and that is the honest finding. In the",
        "published window the top of the table barely moves: by week 10 the mean move across",
        "the whole FBS is under two places, and the teams whose opponents' quality is still",
        "genuinely unknown are the ones with thin, unconnected schedules. The retroactive",
        "product is most valuable exactly where the poll is least confident, which is the",
        "opposite of how retroactive re-ranking usually gets sold.",
        "",
        "## Reproduce it",
        "",
        "```",
        f"uv run cfbpoll grid --season {season} --out out/",
        "```",
        "",
        "`out/retro_movers.csv` carries the top 25 movers for every evaluation week;",
        "`out/ratings_grid.parquet` carries the whole triangle, so any other view of it is a",
        "group-by away.",
        "",
        provenance(),
    ]
    return "\n".join(lines)


# ------------------------------------------------------------- 3. Cincinnati 2021


def cincinnati_2021() -> str:
    season = 2021
    games, buckets, grid = season_frames(season)
    evaluated = buckets[-1]
    live_all, hind_all = retro.surfaces(grid)
    live = ranked(live_all, evaluated.order)
    hind = ranked(hind_all, evaluated.order)

    cin = team_row(hind, "Cincinnati")
    bama = team_row(hind, "Alabama")
    uga = team_row(hind, "Georgia")
    mich = team_row(hind, "Michigan")

    track = (
        retro.movers(live_all, hind_all).filter(pl.col("team") == "Cincinnati").sort("eval_order")
    )
    nd_game = games.filter(
        (pl.col("home_team") == "Notre Dame") & (pl.col("away_team") == "Cincinnati")
    )

    lines = [
        f"# {season}: Cincinnati, the first Group of Five playoff team",
        "",
        POSTSEASON_CAVEAT.format(seasons="2021 and 2022"),
        "",
        "Cincinnati went 13-0, won the American, and became the first team from outside the",
        "Power Five to make the College Football Playoff — at **#4**, behind three one-loss",
        "Power Five teams. The argument at the time was entirely about schedule: had",
        "Cincinnati actually *done* more than Alabama, Michigan and Georgia, or had it only",
        "avoided losing to anybody good? That is precisely the question the résumé rating is",
        "constructed to answer, so it is the natural first test of it.",
        "",
    ]
    lines += power_v0_note()
    lines += [
        "",
        "## The final poll (through conference championships)",
        "",
    ]
    lines += poll_table(live, hind, 12)
    lines += [
        "",
        "For this season the live and hindsight columns are **identical**, and that is not a",
        "bug: with no postseason in the archive, the final evaluation week *is* the final",
        "data window, so R(N, N) and R(N, final) are the same fit. The retroactive view of",
        "2021 lives in the earlier weeks, below.",
        "",
        "## The two numbers, side by side",
        "",
        "| Team | Rec | Résumé | Résumé # | Power | Power # | Gap |",
        "|---|:---:|---:|---:|---:|---:|---:|",
    ]
    for row in (cin, bama, mich, uga):
        mark = "\\*" if row["saturated"] else ""
        lines.append(
            f"| {row['team']} | {row['wins']}-{row['losses']} | {row['resume']:.2f}{mark} "
            f"| {row['rank']} | {row['power']:.2f} | {row['power_rank']} | {row['gap']:+.2f} |"
        )
    lines += [
        "",
        f"**Cincinnati is résumé #{cin['rank']} and power #{cin['power_rank']}.** The committee "
        "put it at #4, which is",
        "almost exactly between the two numbers — and, read charitably, is what a committee",
        'trying to blend "what did you do" with "how good are you" would land on if it did',
        "the blending in its head instead of on paper.",
        "",
        "The résumé number is not saying Cincinnati was the best team in the country. It is",
        "saying that **13-0 against this schedule has no finite quality that explains it** —",
        "the saturation property, which puts every unbeaten team on the bracket. The power",
        f"rating, {cin['power']:.2f} points, is the model's actual estimate of how good "
        f"Cincinnati was, and it",
        f"is {ordinal(cin['power_rank'])}. Publishing both, with the gap "
        f"({cin['gap']:+.2f}) printed between them, is the",
        "whole of report 02 §3.5's argument in one row.",
        "",
    ]
    if nd_game.height:
        g = nd_game.row(0, named=True)
        lines += [
            "The win that carried the résumé is on the schedule: at Notre Dame, "
            f"{g['away_points']}-{g['home_points']}, on",
            f"{g['start_date']:%-d %B %Y}. Notre Dame finished the regular season "
            f"{team_row(hind, 'Notre Dame')['wins']}-"
            f"{team_row(hind, 'Notre Dame')['losses']} and is power "
            f"#{team_row(hind, 'Notre Dame')['power_rank']} here,",
            "so it is a genuinely load-bearing road win against a top-ten team — which is",
            "exactly the kind of thing a résumé rating is supposed to notice and a margin-based",
            "power rating is supposed to under-weight.",
            "",
        ]

    lines += [
        "## The retroactive view: Cincinnati week by week",
        "",
        "Cincinnati was undefeated all season, so its wins-based résumé is pinned at the",
        "bracket in every week and the rank movement below comes entirely from the",
        "margin-aware tie-break and from what the rest of the country learned about",
        "Cincinnati's opponents. The Power column is where the substitution shows.",
        "",
        "| Week | Live # | Hindsight # | Move | Power live | Power hindsight |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for row in track.iter_rows(named=True):
        delta = row["rank_delta"]
        arrow = "—" if delta == 0 else (f"▲{delta}" if delta > 0 else f"▼{-delta}")
        lines.append(
            f"| `{row['eval_label']}` | {row['rank_live']} | {row['rank_hindsight']} | {arrow} "
            f"| {row['power_live']:.2f} | {row['power_hindsight']:.2f} |"
        )
    lines += [
        "",
        "Week 1 is the interesting row: live, Cincinnati is nowhere, because after one game",
        "against nobody in particular a zero-prior ridge knows nothing. In hindsight it is",
        "already a top-ten team's week 1. By week 6 the two columns have converged and stay",
        "converged, which is the divergence curve of report 02 §5.2 behaving itself.",
        "",
        "## The comparison — **not** a target",
        "",
    ]
    lines += cfp_table(season)
    lines += [
        "",
        "Source: the official CFP release of 5 December 2021. This is a human poll. It is a",
        "comparison and never an input (constraint 1).",
        "",
        "**What this document cannot tell you.** Cincinnati lost the Cotton Bowl semifinal to",
        "Alabama 27-6. That game is not in the archive for this season, so it is not in any",
        "number above. A reader who wants to argue that the playoff settled the question is",
        "arguing from evidence this poll has not seen — which is worth saying plainly rather",
        "than letting the omission pass as a result.",
        "",
        "## Reproduce it",
        "",
        "```",
        f"uv run cfbpoll rank --season {season} --through-week {evaluated.week} --out out/",
        f"uv run cfbpoll grid --season {season} --out out/",
        "```",
        "",
        provenance(),
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------- 4. the week-10 poll


def top25() -> str:
    cfg = load_config()
    games, buckets, _ = season_frames(DEMO_SEASON)
    regular = [b for b in buckets if b.season_type == "regular"]
    evaluated = next(b for b in regular if b.week == DEMO_WEEK)
    final = buckets[-1]

    window = windows.games_through(games, season=DEMO_SEASON, week=DEMO_WEEK, season_type="regular")
    power = l4_resume.power_from_l2(window, cfg)
    fitted = l4_resume.fit(window, cfg, power=power)
    live = retro.cell(games, evaluated, evaluated, cfg, power=power)
    hind = retro.cell(games, evaluated, final, cfg)
    live_r = live.filter(pl.col("rank").is_not_null())
    hind_r = hind.filter(pl.col("rank").is_not_null())

    fbs_only = window.filter((pl.col("home_class") == "fbs") & (pl.col("away_class") == "fbs"))
    l2 = power.l2
    assert l2 is not None

    lines = [
        f"# The poll — {DEMO_SEASON} through regular week {DEMO_WEEK}",
        "",
        "The headline layer, mid-season: teams ranked by the **L4 résumé rating**, with the",
        "**Power rating** and the gap between them beside every team (report 02 §3.5).",
        "",
    ]
    lines += power_v0_note()
    lines += [
        "",
        "## What went into it",
        "",
        "| | |",
        "|---|---|",
        f"| Games in the fit | {l2.n_games:,} |",
        f"| ... of which FBS-vs-FBS | {fbs_only.height:,} |",
        f"| Teams with their own coefficient | {l2.n_teams} |",
        f"| Ridge lambda (5-fold CV on games) | {l2.lam:g} |",
        f"| Home field, fitted and unpenalised (L2 units) | {l2.home_field:.3f} |",
        f"| Points-scale map `b` (L2 → points) | {power.scale:.3f} |",
        f"| Home field on the points scale | {power.home_field:.3f} |",
        f"| sigma | {fitted.sigma} |",
        f"| Compression scale C | {cfg['margin']['c']:g} |",
        f"| Win premium beta_w | {cfg['margin']['beta_w']:g} |",
        f"| Teams saturated at the q bound | {fitted.as_params()['n_saturated_high']} |",
        "",
        "Every FCS team in the schedule holds its own coefficient in the same fit under the",
        "same penalty — no pooled node (report 02 §3.7) — and gets its own résumé too. They",
        "are omitted from the table below because this is a college football poll, not",
        f"because they are hidden: `out/ratings_live.parquet` carries all {live.height} teams.",
        "",
        "## Top 25",
        "",
    ]
    lines += poll_table(live_r, hind_r, 25)
    lines += ["", *saturation_note(), ""]

    uga = team_row(live_r, "Georgia")
    fsu = team_row(live_r, "Florida State")
    ksu = team_row(live_r, "Kansas State")
    lines += [
        "## Reading it honestly",
        "",
        f"Undefeated Georgia is résumé #{uga['rank']} and power #{uga['power_rank']}; undefeated "
        f"Florida State is résumé",
        f"#{fsu['rank']} and power #{fsu['power_rank']}. On the L2-only build that shipped before "
        "this layer existed,",
        "those two sat at 10th and 5th on the power number alone and looked like a bug. They",
        "were not a bug; they were half the picture. A margin-based power rating discounts a",
        "run of narrow wins, and a résumé rating does the opposite, and report 02 §3.5's",
        "answer is to print both and show the gap.",
        "",
        f"Kansas State at résumé #{ksu['rank']} on a {ksu['wins']}-{ksu['losses']} record, "
        f"against power #{ksu['power_rank']}, is the same effect",
        "in the other direction: three close losses to good teams. `beta_w = "
        f"{cfg['margin']['beta_w']:g}` is the knob",
        "that governs exactly this, it is published on every artifact, and report 02 §7.4 is",
        "explicit that its value is a decision for people rather than for a grid search.",
        "",
        "## Reproduce it",
        "",
        "```",
        f"uv run cfbpoll rank --season {DEMO_SEASON} --through-week {DEMO_WEEK} --out out/",
        "```",
        "",
        provenance(),
    ]
    return "\n".join(lines)


# ------------------------------------------------------------------- 5. the backtest


def _fmt(value: float | None, spec: str) -> str:
    if value is None:
        return "-"
    return format(value, spec)


def backtest_report() -> str:
    result = walkforward.run_backtest(seasons=TUNE_SEASONS, systems=SYSTEMS)
    protocol = result["protocol"]
    systems = result["systems"]
    order = ["l2", "srs", "elo", "colley", "winpct", "random_walker", "home_team"]
    label = {
        "resume": "**L4 résumé (ours)**",
        "l2": "**L2 (ours)**",
        "srs": "SRS (±24/±7)",
        "elo": "Elo (K=25, MOV)",
        "colley": "Colley",
        "winpct": "Win %",
        "random_walker": "Random walker",
        "home_team": "Home team wins",
    }

    def table(cut: str, caption: str) -> list[str]:
        rows = [
            "",
            f"### {caption}",
            "",
            "| System | n | SU % | MAE | RMSE | Brier | Log loss | Max calib. dev. |",
            "|---|---:|---:|---:|---:|---:|---:|---:|",
        ]
        for name in order:
            block = systems[name][cut].get("fbs_vs_fbs")
            if not block:
                continue
            rows.append(
                f"| {label[name]} | {block['n_games']} | {block['su_accuracy'] * 100:.2f} "
                f"| {block['mae']:.3f} | {block['rmse']:.3f} | {block['brier']:.4f} "
                f"| {block['log_loss']:.4f} | {block['max_calibration_deviation_pp']:.2f} pp |"
            )
        return rows

    lines = [
        "# Walk-forward backtest, 2021-2023 (tune seasons only)",
        "",
        "**2024 (validate) and 2025 (holdout) are untouched.** The harness refuses to score",
        "2025 without an explicit `--unlock-holdout`, and no code path in this repository",
        "passes it (report 02 §5.1). Nothing below has been tuned against anything: the",
        "config's starting values are the research report's, and no grid has been searched.",
        "",
        "## Protocol",
        "",
        "- To predict week N, fit on data through week N-1 of the **same season only**. No",
        "  prior seasons, ever (constraint 2), and no future games (`prior_seasons_used`:",
        f"  `{protocol['prior_seasons_used']}`).",
        "- Evaluation universe: FBS-vs-FBS. FBS-vs-FCS games, non-CFP bowls and CFP games",
        "  are scored separately below, because they measure different things.",
        f"- Win probability = Phi(margin / sigma) with sigma = {protocol['sigma']}"
        " (report 02 §3.4, §5.4).",
        "- Every system's ratings are mapped to the points scale by one OLS per system per",
        "  week, fitted on the out-of-sample predictions already accumulated that season.",
        "  Elo lives on a 400-point logit scale and win percentage on [0, 1]; without this",
        "  the MAE column would be meaningless for five of the seven rows. Straight-up",
        "  accuracy is unaffected - it is invariant to a positive affine map.",
        "- **The L4 résumé is not in the predictive table.** It is a retrodictive rating by",
        "  construction (report 02 §3.5): every undefeated team sits on the same q bound, and",
        "  it is a strongly nonlinear function of Power, so a single affine map per week",
        "  cannot describe it. It therefore predicts through its Power source - which would",
        "  reproduce L2's row exactly - and is scored below on **violations**, which is the",
        "  metric it is for.",
        "",
        "## The headline table",
        "",
        f"Weeks {protocol['headline_start_week']}+ is the window the project actually intends",
        "to publish (report 02 §4): before then the schedule graph is barely connected and a",
        "zero-prior system openly does not know anything yet. Both cuts are shown, because",
        "reporting only the flattering one would be the exact failure this project exists to",
        "avoid.",
    ]
    lines += table("segments_from_headline_week", "Weeks 5+ (the published window)")
    lines += table("segments", "Weeks 2+ (everything the harness can score)")

    lines += [
        "",
        "## What that says",
        "",
        "- From week 5 on, L2 leads **every** predictive metric: accuracy, MAE, RMSE, Brier,",
        "  log loss and calibration. That is the Barrow et al. result (report 02 §2.15) -",
        "  least squares on score differential is the best-supported family for college",
        "  football - reproduced on 2021-2023 with an independent implementation.",
        "- Over weeks 2+ the ordering is not clean: SRS edges L2 on MAE and Elo on accuracy,",
        "  both by fitting the near-noise weeks slightly better. A zero-prior system has no",
        "  business being confident in September and this is the number that shows it.",
        "- The random walker underperforms here, which is a real disagreement with Barrow et",
        "  al. Two candidate explanations, neither verified: their implementation is",
        "  full-season rather than walk-forward, and this one is margin-blind by",
        "  construction. It stays in the baseline set.",
        "- Win percentage is beaten decisively on margin error by everything with an",
        "  opponent adjustment, which is what constraint 3 exists to buy.",
        "- Non-CFP bowls are worse than a coin flip for every system in the table. That is",
        "  the roster-availability problem of report 02 §3.8 showing up as a number, and it",
        "  is why those games carry a 0.25 weight in the fit and are never pooled into the",
        "  headline.",
        "",
        "## Retrodictive violations — the metric the headline layer is for",
        "",
        "Violations are games whose loser the final full-season rating ranks above the",
        "winner - the canonical retrodictive metric (report 02 §2.12). Churn is the mean",
        "absolute week-over-week rank change across FBS teams.",
        "",
        "| System | Violation rate | Violations / games | Mean rank churn |",
        "|---|---:|---:|---:|",
    ]
    for name in ["resume", *order]:
        block = systems[name]
        rows = block["retrodictive_violations"]
        count = (
            f"{int(sum(r['violations'] for r in rows))} / {int(sum(r['games'] for r in rows))}"
            if rows
            else "-"
        )
        lines.append(
            f"| {label[name]} | {_fmt(block['retrodictive_violation_rate'], '.4f')} "
            f"| {count} | {_fmt(block['rank_churn']['mean_all'], '.2f')} |"
        )

    rate = {n: systems[n]["retrodictive_violation_rate"] for n in ["resume", *order[:-1]]}
    gate = systems["resume"]["gate"]["violations_vs_baselines"]
    lines += [
        "",
        "**The résumé clears the gate the L2-only build missed.** `configs/default.toml` asks",
        "for a violation rate at or below Colley and SRS (`violations_must_beat`); the résumé",
        f"is at {rate['resume']:.4f} against Colley's {rate['colley']:.4f} and SRS's "
        f"{rate['srs']:.4f}, and the harness now",
        f"reports that criterion as `{gate}` rather than as an undecided null. It also beats",
        f"its own Power rating by {(rate['l2'] - rate['resume']) * 100:.2f} points of violation "
        "rate - 2021: 135 vs 159, 2022: 159",
        "vs 163, 2023: 141 vs 145 - which is the point of building the layer.",
        "",
        f"**It does not beat win percentage, which is at {rate['winpct']:.4f}, and that is worth",
        "saying rather than burying.** Violations count only who beat whom; a rating that is",
        "purely a function of record is close to the floor on a metric that ignores schedule",
        "entirely. The roughly two points of violation rate the résumé gives up is the price",
        "of caring who you played, which is constraint 3. A poll optimised for this metric",
        "alone would be a win-percentage poll, and that is not a thing anyone wants.",
        "",
        f"On the pooled 2021-2023 number the résumé and Colley are exactly tied "
        f"({int(sum(r['violations'] for r in systems['resume']['retrodictive_violations']))} each,",
        "of 2,216 games). They differ season by season and the aggregate coincidence is",
        "just that.",
        "",
        "Saturation cannot flatter this number, and the reason is structural rather than",
        "empirical: a team saturated at the top never lost a game, and a team saturated at",
        "the bottom never won one, so no tie at either bound can ever appear in a",
        "winner/loser pair.",
        "",
        "## Segments reported separately",
        "",
        "| Segment | n | SU % | MAE | Why it is separate |",
        "|---|---:|---:|---:|---|",
    ]
    why = {
        "fbs_vs_fbs": "the evaluation universe",
        "fbs_vs_fcs": "easy games; pooling them in inflates accuracy",
        "bowl": "non-CFP bowls have a systematic roster-availability problem (§3.8)",
        "cfp": "rosters intact, but a handful of games a year",
    }
    for segment, block in systems["l2"]["segments"].items():
        lines.append(
            f"| `{segment}` | {block['n_games']} | {block['su_accuracy'] * 100:.2f} "
            f"| {block['mae']:.3f} | {why[segment]} |"
        )

    early = [c for c in result["connectivity"] if c["season"] == 2023 and c["week"] <= 3]
    late = [c for c in result["connectivity"] if c["season"] == 2023 and c["week"] == 10]
    lines += [
        "",
        "## Why the early weeks look the way they do",
        "",
        "The schedule graph is the reason, and it is measurable rather than an excuse.",
        "Each row is the training window a fit for that week would have seen, in 2023:",
        "",
        "| Fit window | Teams | Components | Largest component |",
        "|---|---:|---:|---:|",
    ]
    for c in (early[:2] + late)[:3]:
        lines.append(
            f"| 2023 before week {c['week']} | {c['n_teams']:.0f} | {c['n_components']:.0f} "
            f"| {c['largest_component_share'] * 100:.1f}% |"
        )
    lines += [
        "",
        "A fragmented graph is exactly what makes SRS near-singular and a zero-prior",
        "ranking wild in September. Our ridge term keeps the system solvable throughout -",
        "L + lambda*I is positive definite for any lambda > 0 - but solvable is not the",
        "same as informative, which is why report 02 §4 recommends publishing a",
        "connectivity report instead of a poll until week 5. The résumé layer gives that",
        "the sharpest possible statement: through week 3 of 2023, 46 of 133 ranked teams",
        "are still undefeated and therefore saturated at the q bound, i.e. the wins-based",
        "résumé cannot tell a third of the league apart.",
        "",
        "## Reproduce it",
        "",
        "```",
        "uv run cfbpoll backtest --systems resume,l2,colley,srs,elo,walker,winpct \\",
        "  --seasons 2021-2023",
        "```",
        "",
        "The full metrics tree, including the per-week table and every calibration decile,",
        "is written to `out/backtest_metrics.json`.",
        "",
        provenance(),
    ]
    return "\n".join(lines)


def _valid_json(obj: object) -> object:
    """NaN is not JSON. A week with no shared teams has no churn; that is a null."""
    if isinstance(obj, dict):
        return {k: _valid_json(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_valid_json(v) for v in obj]
    if isinstance(obj, float) and not math.isfinite(obj):
        return None
    return obj


def main() -> None:
    DEMO.mkdir(exist_ok=True)
    (DEMO / "2023-final-poll.md").write_text(final_poll_2023(), encoding="utf-8")
    (DEMO / "2023-retro-movers.md").write_text(retro_movers_2023(), encoding="utf-8")
    (DEMO / "2021-cincinnati.md").write_text(cincinnati_2021(), encoding="utf-8")
    (DEMO / f"{DEMO_SEASON}-w{DEMO_WEEK}-top25.md").write_text(top25(), encoding="utf-8")
    (DEMO / "backtest-2021-2023.md").write_text(backtest_report(), encoding="utf-8")

    result = walkforward.run_backtest(seasons=TUNE_SEASONS, systems=SYSTEMS)
    (DEMO / "backtest-2021-2023.json").write_text(
        json.dumps(
            _valid_json({"protocol": result["protocol"], "systems": result["systems"]}),
            indent=2,
            sort_keys=True,
            default=float,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {sorted(p.name for p in DEMO.iterdir())}")


if __name__ == "__main__":
    main()
